-- MySQL Script generated by MySQL Workbench
-- Mon 28 Feb 2022 05:20:16 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema micro_blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema micro_blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `micro_blog` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `micro_blog` ;

-- -----------------------------------------------------
-- Table `micro_blog`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micro_blog`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(150) NOT NULL,
  `firstname` VARCHAR(150) NOT NULL,
  `lastname` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `age` SMALLINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micro_blog`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micro_blog`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micro_blog`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micro_blog`.`user_role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_fk` INT UNSIGNED NOT NULL,
  `role_fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role_user_idx` (`user_fk` ASC),
  INDEX `fk_user_role_role_idx` (`role_fk` ASC),
  CONSTRAINT `fk_user_role_user`
    FOREIGN KEY (`user_fk`)
    REFERENCES `micro_blog`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_role_role`
    FOREIGN KEY (`role_fk`)
    REFERENCES `micro_blog`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micro_blog`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micro_blog`.`article` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  `date_add` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_article_user_idx` (`user_fk` ASC),
  CONSTRAINT `fk_article_user`
    FOREIGN KEY (`user_fk`)
    REFERENCES `micro_blog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micro_blog`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micro_blog`.`comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `user_fk` INT UNSIGNED NOT NULL,
  `article_fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_article_idx` (`article_fk` ASC),
  INDEX `fk_comments_user_idx` (`user_fk` ASC),
  CONSTRAINT `fk_comments_article`
    FOREIGN KEY (`article_fk`)
    REFERENCES `micro_blog`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_user`
    FOREIGN KEY (`user_fk`)
    REFERENCES `micro_blog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
